language: java
jdk: openjdk8
sudo: false
deploy:
  provider: releases
  api_key:
    secure: dMayYe6XnGGOTydZxSpIW7LMt3ATTzSPG/fgIAr2LqKXI7t0cB3PyMUtHMRLXij96jCRMes38UJ+1ELuVwEW9Gf7lyY58rPkoS2fxaPweYYkm9qgcyCgrRFLSAnLcBODnXFoEv4A/YDS18WiMo+XH7fedzkfvs8mYtv5x8pz5DY=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-bamboo-plugin

