language: java
jdk: openjdk8
sudo: false
notifications:
  slack:
    secure: KQSI+S0Xa5u3lEoF1X14atOHUGWie1hB7AIx11VlXDBstgooeP7/zPwlPwFd/AaN19Ac72psqcqZPetF4hQTIkQ+OXoldnbhXCb6lR3REUJXGFPi3+yg5AM425SF250Se9KJTLlBg+3oOhy0ZwTz8mvVtD+Shpl+bjOOpYnZsaw=
deploy:
  provider: releases
  api_key:
    secure: FdVcS+GUeR7zI8cCgOmUzvDB9ZcDAYoP9h48cnStVMKzYDb85aQ9DwKrPrIJiDOmTFyQ10tQjasgKLcHU/ECG0fvV6ZF7NNPVFQOKkDDXVkvcQ8ivSkFf7t8dIhcljNtXvmZHgzPK9ZZddq/jn+Nqv4d1qYY6yE7hST9lmvv5aU=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-bamboo-plugin
